title: DongKyu Kwak
description: Haptic Researcher
site_title: 'DK'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Kwak-DongKyu
blog_url: https://www.nagekar.com
email: kig160@kaist.ac.kr
keybase_username: dk
twitter_username: dk
reddit_username: dk

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
